project_structure/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
]

weather/urls.py
from django.urls import path
from . import views


app_name = 'weather'

urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    # Search page.
    path('search/', views.search, name='search'),
    #Delete city.
    path('delete/<city_name>/', views.delete_city, name='delete_city'),
    #Deelet all cities.
    path('deleteall/', views.delete_all, name='delete_all'),
]       

weather/models.py
from django.db import models

class City(models.Model):
    name = models.CharField(max_length=25)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'cities'

weather/forms.py
from typing import Text
from django.forms import ModelForm, TextInput, widgets
from .models import City

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {'name' : TextInput(attrs={'class' : 'form-control', 'placeholder' : 'City Name'})}

weather/views.py
from django.shortcuts import redirect, render, redirect
from .models import City
from .forms import CityForm
import requests
import os

def index(request):

    return render(request, 'weather/index.html')

def search(request):

    url = os.environ.get('url')
    
    err_msg = ''
    message = ''

    
    if request.method == 'POST':
        form = CityForm(request.POST)

        if form.is_valid():
            new_city = form.cleaned_data['name']
            existing_city_count = City.objects.filter(name=new_city).count()

            if existing_city_count == 0:
                r = requests.get(url.format(new_city)).json()

                if r['cod'] == 200:
                    form.save()
                else:
                    err_msg = 'City does not exist.'

            else:
                err_msg = 'City already ecists.'

        if err_msg:
            message = err_msg
        else:
            message = 'City was added!'

    form = CityForm()

    cities = City.objects.all()

    weather_data = []

    for city in cities:

        r = requests.get(url.format(city)).json()

        city_weather = {
            'city' : city.name,
            'temperature' : r['main']['temp'],
            'description' : r['weather'][0]['description'],
            'icon' : r['weather'][0]['icon']
        }

        weather_data.append(city_weather)

    context = {
        'weather_data' : weather_data,
        'form' : form,
        'message' : message,
        }
    return render(request, 'weather/search.html', context)


def delete_city(request, city_name):

    City.objects.get(name=city_name).delete()

    return redirect('weather:search')

def delete_all(request):

    cities = City.objects.all()

    for city in cities:
        City.objects.get(name=city).delete()
    
    return redirect('weather:search')

weather/templates/weather/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    {% block title %}

    <title>Weather</title>

    {% endblock title %}
    
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>

    <nav class="navbar sticky-top navbar-dark bg-dark">
        <form class="form-inline">
           <a class="btn btn-outline-success" href="{% url 'weather:index' %}" role="button">Weather</a>
        </form>
    </nav>

     <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

weather/templates/weather/index.html
{% extends 'weather/base.html' %}


{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Find out the weather!</h1>
            <p class="lead">This website uses open world API to show live weather anywhere in the world!</p>
                <hr class="my-4">
            <p>Click the button below to start finding out the weather.</p>
            <p class="lead">
            <a class="btn btn-outline-success btn-lg" href="{% url 'weather:search' %}" role="button">Search</a>
        </p>
    </div>
{% endblock content %}

weather/templates/weather/search.html
{% extends "weather/base.html" %}

{% block title %}

    <title>Search</title>

{% endblock title %}

{% block content %}

<form method='post' action="{% url 'weather:search' %}">

    {% csrf_token %}
    {{ form.as_p }}
    <button name='submit' class='btn btn-outline-success mb-2 mt-2'>Add City</button>

<form>

<a role="button" href="{% url 'weather:delete_all' %}" class="btn btn-danger m">Delete All</a>

{% for weather in weather_data %}

    <div class="card text-center mb-3" style="background-color: #BDCEDE">
        <img class="card-img mx-auto" style="max-width: 5rem;" src="http://openweathermap.org/img/w/{{ weather.icon }}.png" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{ weather.city }}</h5>
            <p class="card-text">{{ weather.temperature }}°F</p>
        </div>
            <li class="list-group-item" style="background-color: #BDCEDE">{{ weather.description }}</li>
            <ul class="list-group list-group-flush">
        <div class="card-body">
            <a role="button" href="{% url 'weather:delete_city' weather.city %}" class="">Delete</a>
        </div>
    </div>
 
{% endfor %}

{% endblock content %}